DEVICE_NAME_            : "Focusrite 2i2"
pcm_name_               : "hw:0,0"
pcm_frames_             : 100
pcm_sampleRate_         : 44100
pcm_available_channels_ : 2
pcm_using_channels_     : 2
pcm_loops_              : 0
